DROP TABLE GRZYBOW1.DOCUMENTATION_FILE;
DROP TABLE GRZYBOW1.PATIENT_DOCUMENTATION;
DROP TABLE GRZYBOW1.APPOINTMENT;
DROP TABLE GRZYBOW1.WORKING_HOURS;
DROP TABLE GRZYBOW1.CHANGE_IN_WORKING_HOURS;
DROP TABLE GRZYBOW1.DAY_OF_THE_WEEK;
DROP TABLE GRZYBOW1.EMPLOYEE;
DROP TABLE GRZYBOW1.PATIENT;
DROP TABLE GRZYBOW1.ACCOUNT;
DROP TABLE GRZYBOW1.EMPLOYEE_TYPE;
DROP TABLE GRZYBOW1.ROLE;



 CREATE TABLE "GRZYBOW1"."ROLE" 
   (	"ID_ROLE" NUMBER NOT NULL ENABLE, 
	"ROLE" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	 CONSTRAINT "ROLE_PK" PRIMARY KEY ("ID_ROLE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
  
  

CREATE TABLE "GRZYBOW1"."ACCOUNT" 
   (	"ID_ACCOUNT" NUMBER NOT NULL ENABLE, 
	"USERNAME" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"PASSWORD" VARCHAR2(100 BYTE) NOT NULL ENABLE, 
	"USER_TYPE" NUMBER NOT NULL ENABLE, 
	 CONSTRAINT "ACCOUNT_PK" PRIMARY KEY ("ID_ACCOUNT")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE, 
	 CONSTRAINT "FK_ID_TROLE" FOREIGN KEY ("USER_TYPE")
	  REFERENCES "GRZYBOW1"."ROLE" ("ID_ROLE") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
  
  
  
  CREATE TABLE "GRZYBOW1"."DAY_OF_THE_WEEK" 
   (	"ID_DAY_OF_THE_WEEK" NUMBER NOT NULL ENABLE, 
	"NAME" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	 CONSTRAINT "DAY_OF_THE_WEEK_PK" PRIMARY KEY ("ID_DAY_OF_THE_WEEK")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
  
  
  
   CREATE TABLE "GRZYBOW1"."EMPLOYEE_TYPE" 
   (	"ID_EMPLOYEE_TYPE" NUMBER NOT NULL ENABLE, 
	"TITLE" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	 CONSTRAINT "EMPLOYEE_TYPE_PK" PRIMARY KEY ("ID_EMPLOYEE_TYPE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
  
  
  
 CREATE TABLE "GRZYBOW1"."PATIENT" 
   (	"ID_PATIENT" NUMBER NOT NULL ENABLE, 
	"NAME" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"SURNAME" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"DATE_OF_BIRTH" DATE NOT NULL ENABLE, 
	"ADDRESS" VARCHAR2(64 BYTE) NOT NULL ENABLE, 
	"ID_ACCOUNT" NUMBER NOT NULL ENABLE, 
	"GENDER" CHAR(1 BYTE), 
	 CONSTRAINT "PATIENT_PK" PRIMARY KEY ("ID_PATIENT")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE, 
	 CONSTRAINT "P_ID_ACCOUNT_FK" FOREIGN KEY ("ID_ACCOUNT")
	  REFERENCES "GRZYBOW1"."ACCOUNT" ("ID_ACCOUNT") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
  
  
  
    CREATE TABLE "GRZYBOW1"."EMPLOYEE" 
   (	"ID_EMPLOYEE" NUMBER NOT NULL ENABLE, 
	"NAME" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"SURNAME" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"DATE_OF_BIRTH" DATE NOT NULL ENABLE, 
	"ADDRESS" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"ID_ACCOUNT" NUMBER NOT NULL ENABLE, 
	"ID_EMPLOYEE_TYPE" NUMBER NOT NULL ENABLE, 
	 CONSTRAINT "EMPLOYEE_PK" PRIMARY KEY ("ID_EMPLOYEE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE, 
	 CONSTRAINT "E_ID_ACCOUNT_FK" FOREIGN KEY ("ID_ACCOUNT")
	  REFERENCES "GRZYBOW1"."ACCOUNT" ("ID_ACCOUNT") ENABLE, 
	 CONSTRAINT "E_ID_EMPLOYEE_TYPE" FOREIGN KEY ("ID_EMPLOYEE_TYPE")
	  REFERENCES "GRZYBOW1"."EMPLOYEE_TYPE" ("ID_EMPLOYEE_TYPE") ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
  
  
  
 CREATE TABLE "GRZYBOW1"."APPOINTMENT" 
   (	"ID_APPOINTMENT" NUMBER NOT NULL ENABLE, 
	"ID_EMPLOYEE" NUMBER NOT NULL ENABLE, 
	"ID_PATIENT" NUMBER, 
	"A_DATE" DATE NOT NULL ENABLE, 
	"A_HOUR" NUMBER(3,0) NOT NULL ENABLE, 
	 CONSTRAINT "CALENDAR_PK" PRIMARY KEY ("ID_APPOINTMENT")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE, 
	 CONSTRAINT "EMPLOYEE_FK" FOREIGN KEY ("ID_EMPLOYEE")
	  REFERENCES "GRZYBOW1"."EMPLOYEE" ("ID_EMPLOYEE") ENABLE, 
	 CONSTRAINT "PATIENT_FK" FOREIGN KEY ("ID_PATIENT")
	  REFERENCES "GRZYBOW1"."PATIENT" ("ID_PATIENT") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
  
  
  
    CREATE TABLE "GRZYBOW1"."CHANGE_IN_WORKING_HOURS" 
   (	"ID_CHANGE_IN_WORK_HOURS" NUMBER NOT NULL ENABLE, 
	"ID_EMPLOYEE" NUMBER NOT NULL ENABLE, 
	"DATE_FROM" DATE NOT NULL ENABLE, 
	"DAY_OF_THE_WEEK" NUMBER NOT NULL ENABLE, 
	"TIME_FROM" VARCHAR2(6 BYTE) NOT NULL ENABLE, 
	"TIME_TO" VARCHAR2(6 BYTE) NOT NULL ENABLE, 
	"ACTION" CHAR(1 BYTE) NOT NULL ENABLE, 
	 CONSTRAINT "CHANGE_IN_WORK_HOURS_PK" PRIMARY KEY ("ID_CHANGE_IN_WORK_HOURS")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "USERS"  ENABLE, 
	 CONSTRAINT "CIWH_ID_EMPLOYEE_FK" FOREIGN KEY ("ID_EMPLOYEE")
	  REFERENCES "GRZYBOW1"."EMPLOYEE" ("ID_EMPLOYEE") ENABLE, 
	 CONSTRAINT "CIWH_DAY_OF_THE_WEEK" FOREIGN KEY ("DAY_OF_THE_WEEK")
	  REFERENCES "GRZYBOW1"."DAY_OF_THE_WEEK" ("ID_DAY_OF_THE_WEEK") ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
  
  
  
   CREATE TABLE "GRZYBOW1"."WORKING_HOURS" 
   (	"ID_WORKING_HOURS" NUMBER NOT NULL ENABLE, 
	"ID_EMPLOYEE" NUMBER NOT NULL ENABLE, 
	"ID_DAY_OF_THE_WEEK" NUMBER NOT NULL ENABLE, 
	"FROM_TIME" VARCHAR2(6 BYTE) NOT NULL ENABLE, 
	"TO_TIME" VARCHAR2(6 BYTE) NOT NULL ENABLE, 
	 CONSTRAINT "WORK_HOURS_PK" PRIMARY KEY ("ID_WORKING_HOURS")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE, 
	 CONSTRAINT "WH_EMPLOYEE_FK" FOREIGN KEY ("ID_EMPLOYEE")
	  REFERENCES "GRZYBOW1"."EMPLOYEE" ("ID_EMPLOYEE") ENABLE, 
	 CONSTRAINT "WG_DAY_FK" FOREIGN KEY ("ID_DAY_OF_THE_WEEK")
	  REFERENCES "GRZYBOW1"."DAY_OF_THE_WEEK" ("ID_DAY_OF_THE_WEEK") ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
  
  
  
    CREATE TABLE "GRZYBOW1"."DOCUMENTATION_FILE" 
   (	"ID_DOCUMENTATION_FILE" NUMBER NOT NULL ENABLE, 
	"FILE_NAME" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"DOCUMENTATION_FILE" BLOB NOT NULL ENABLE, 
	"ID_PATIENT_DOCUMENTATION" NUMBER NOT NULL ENABLE, 
	 CONSTRAINT "FILES_PK" PRIMARY KEY ("ID_DOCUMENTATION_FILE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "USERS"  ENABLE, 
	 CONSTRAINT "DF_ID_PATIENT_DOCUMENTATION_FK" FOREIGN KEY ("ID_PATIENT_DOCUMENTATION")
	  REFERENCES "GRZYBOW1"."PATIENT_DOCUMENTATION" ("ID_PATIENT_DOCUMENTATION") ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" 
 LOB ("DOCUMENTATION_FILE") STORE AS SECUREFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES ) ;
  
  
  CREATE TABLE "GRZYBOW1"."PATIENT_DOCUMENTATION" 
   (	"ID_PATIENT_DOCUMENTATION" NUMBER NOT NULL ENABLE, 
	"ID_EMPLOYEE" NUMBER NOT NULL ENABLE, 
	"ID_PATIENT" NUMBER NOT NULL ENABLE, 
	"TIME_OF_INSCRIPTION" TIMESTAMP (6) NOT NULL ENABLE, 
	"TITLE" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"TEXT" VARCHAR2(256 BYTE) NOT NULL ENABLE, 
	 CONSTRAINT "PATIENT_DOCUMENTATION_PK" PRIMARY KEY ("ID_PATIENT_DOCUMENTATION")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE, 
	 CONSTRAINT "DOC_PATIENT_FK" FOREIGN KEY ("ID_PATIENT")
	  REFERENCES "GRZYBOW1"."PATIENT" ("ID_PATIENT") ENABLE, 
	 CONSTRAINT "DOC_EMPLOYEE" FOREIGN KEY ("ID_EMPLOYEE")
	  REFERENCES "GRZYBOW1"."EMPLOYEE" ("ID_EMPLOYEE") ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;

  
  
   CREATE SEQUENCE  "GRZYBOW1"."SEQ_ACCOUNT"  MINVALUE 1 MAXVALUE 999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOPARTITION ;

   
   
   CREATE SEQUENCE  "GRZYBOW1"."SEQ_APPOINTMENT"  MINVALUE 1 MAXVALUE 99999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOPARTITION ;

   
   
   CREATE SEQUENCE  "GRZYBOW1"."SEQ_CHANGE_IN_WORKING_HOURS"  MINVALUE 1 MAXVALUE 999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOPARTITION ;

   
   
   CREATE SEQUENCE  "GRZYBOW1"."SEQ_DAY_OF_THE_WEEK"  MINVALUE 1 MAXVALUE 99999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOPARTITION ;

   
   
   CREATE SEQUENCE  "GRZYBOW1"."SEQ_DOCUMENTATION_FILE"  MINVALUE 1 MAXVALUE 999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOPARTITION ;

   
   
   CREATE SEQUENCE  "GRZYBOW1"."SEQ_EMPLOYEE"  MINVALUE 1 MAXVALUE 99999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOPARTITION ;

   
   
   CREATE SEQUENCE  "GRZYBOW1"."SEQ_EMPLOYEE_TYPE"  MINVALUE 1 MAXVALUE 9999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOPARTITION ;

   
   
   CREATE SEQUENCE  "GRZYBOW1"."SEQ_PATIENT"  MINVALUE 1 MAXVALUE 99999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOPARTITION ;

   
   
   CREATE SEQUENCE  "GRZYBOW1"."SEQ_PATIENT_DOCUMENTATION"  MINVALUE 1 MAXVALUE 9999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOPARTITION ;

   
   
   CREATE SEQUENCE  "GRZYBOW1"."SEQ_WORKING_HOURS"  MINVALUE 1 MAXVALUE 99999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOPARTITION ;




  
  
  
  
  
  
  
  
  
  
  
  