--dane testowe
INSERT INTO GRZYBOW1.CHANGE_IN_WORKING_HOURS VALUES(SEQ_CHANGE_IN_WORKING_HOURS.NEXTVAL,'5',CURRENT_DATE, '5', '8:00','20:00','a');
INSERT INTO GRZYBOW1.CHANGE_IN_WORKING_HOURS VALUES(SEQ_CHANGE_IN_WORKING_HOURS.NEXTVAL,'6',CURRENT_DATE, '5', '10:00','19:00','a');

INSERT INTO GRZYBOW1.CHANGE_IN_WORKING_HOURS VALUES(SEQ_CHANGE_IN_WORKING_HOURS.NEXTVAL,'5',CURRENT_DATE, '5', '8:00','20:00','d');
INSERT INTO GRZYBOW1.CHANGE_IN_WORKING_HOURS VALUES(SEQ_CHANGE_IN_WORKING_HOURS.NEXTVAL,'6',CURRENT_DATE, '5', '10:00','19:00','d');
INSERT INTO GRZYBOW1.CHANGE_IN_WORKING_HOURS VALUES(SEQ_CHANGE_IN_WORKING_HOURS.NEXTVAL,'7',CURRENT_DATE+1, '5', 'test','test','a');
INSERT INTO GRZYBOW1.CHANGE_IN_WORKING_HOURS VALUES(SEQ_CHANGE_IN_WORKING_HOURS.NEXTVAL,'8',CURRENT_DATE+2, '5', 'test','test','a');



--procedura
create or replace PROCEDURE UPDATE_WORKING_HOURS IS  
  count_index NUMBER;
  row_index NUMBER;
  action CHAR(1 BYTE);
  employee NUMBER;
  day_of_the_week NUMBER;
  time_from VARCHAR2 (6 BYTE);
  time_to VARCHAR2 (6 BYTE);  
BEGIN
    SELECT COUNT(ID_CHANGE_IN_WORK_HOURS) INTO count_index FROM GRZYBOW1.CHANGE_IN_WORKING_HOURS WHERE to_char(DATE_FROM,'DD-MON-YY') = to_char(CURRENT_DATE,'DD-MON-YY');  
  
    WHILE count_index > 0 LOOP  
      SELECT ID_CHANGE_IN_WORK_HOURS INTO row_index FROM GRZYBOW1.CHANGE_IN_WORKING_HOURS WHERE to_char(DATE_FROM,'DD-MON-YY') = to_char(CURRENT_DATE,'DD-MON-YY') FETCH FIRST ROW ONLY;
      SELECT ACTION INTO action FROM GRZYBOW1.CHANGE_IN_WORKING_HOURS WHERE ID_CHANGE_IN_WORK_HOURS = row_index;
      SELECT ID_EMPLOYEE INTO employee FROM GRZYBOW1.CHANGE_IN_WORKING_HOURS WHERE ID_CHANGE_IN_WORK_HOURS = row_index;
      SELECT DAY_OF_THE_WEEK INTO day_of_the_week FROM GRZYBOW1.CHANGE_IN_WORKING_HOURS WHERE ID_CHANGE_IN_WORK_HOURS = row_index;
      SELECT TIME_FROM INTO time_from FROM GRZYBOW1.CHANGE_IN_WORKING_HOURS WHERE ID_CHANGE_IN_WORK_HOURS = row_index;
      SELECT TIME_TO INTO time_to FROM GRZYBOW1.CHANGE_IN_WORKING_HOURS WHERE ID_CHANGE_IN_WORK_HOURS = row_index;
      
      CASE
        WHEN action = 'a' THEN
          INSERT INTO GRZYBOW1.WORKING_HOURS VALUES (SEQ_WORKING_HOURS.NEXTVAL,employee,day_of_the_week,time_from,time_to);          
        WHEN action = 'd' THEN 
          DELETE FROM GRZYBOW1.WORKING_HOURS WHERE ID_EMPLOYEE = employee AND DAY_OF_THE_WEEK = day_of_the_week AND TIME_FROM = time_from AND TIME_TO = time_to;
      END CASE;    
      
      DELETE FROM GRZYBOW1.CHANGE_IN_WORKING_HOURS WHERE ID_CHANGE_IN_WORK_HOURS = row_index;
      SELECT COUNT(ID_CHANGE_IN_WORK_HOURS) INTO count_index FROM GRZYBOW1.CHANGE_IN_WORKING_HOURS WHERE to_char(DATE_FROM,'DD-MON-YY') = to_char(CURRENT_DATE,'DD-MON-YY');  
    END LOOP;    
END UPDATE_WORKING_HOURS; 

--uruchamianie
BEGIN
  UPDATE_WORKING_HOURS();
END;